app/serverinventory/forms.py
from wtforms import Form, StringField, TextAreaField, SelectField
from wtforms_sqlalchemy.fields import QuerySelectField
from models import ServerPhyLocation,ServerDatabaseType,ServerOsType,ServerOsVersion

class ServerForm(Form):
    ser_hostname = StringField('Hostname')
    ser_ip = StringField('IP address')
    ser_os_type = SelectField('OS Type',choices=[(g.id, g.ser_os_type) for g in ServerOsType.query])
    ser_os_version = SelectField('OS Version',choices=[(g.id, g.ser_os_version) for g in ServerOsVersion.query])
    ser_description = StringField('Description')
    ser_cpu = StringField('CPU')
    ser_ram = StringField('RAM')
    ser_storage = StringField('Storage')
    ser_phy_location = SelectField('Physical Location',choices=[(g.id, g.ser_phy_location) for g in ServerPhyLocation.query])
    ser_database_type = SelectField('Database Type',choices=[(g.id, g.ser_database_type) for g in ServerDatabaseType.query])

app/serverinventory/blueprint.py
from flask import Blueprint
from flask import render_template
from models import ServersInventory,ServerPhyLocation,ServerDatabaseType,ServerOsType,ServerOsVersion
from flask import request
from .forms import ServerForm
from app import db
from flask import redirect,url_for
from flask_security import login_required,roles_required,roles_accepted

serinv = Blueprint('serverinventory',__name__,template_folder='templates')



@serinv.route('/add_ser', methods=['POST','GET'])
def add_server():
    if request.method=='POST':
        ser_hostname = request.form['ser_hostname']
        ser_ip = request.form['ser_ip']
        ser_description = request.form['ser_description']
        ser_cpu = request.form['ser_cpu']
        ser_ram = request.form['ser_ram']
        ser_storage = request.form['ser_storage']
        ser_phy_location = request.form['ser_phy_location']
        ser_os_type = request.form['ser_os_type']
        ser_os_version = request.form['ser_os_version']
        ser_database_type = request.form['ser_database_type']
        try:
            new_server = ServersInventory(ser_hostname = ser_hostname,ser_ip=ser_ip, ser_description=ser_description,ser_cpu=ser_cpu,ser_ram=ser_ram,ser_storage=ser_storage,\
                 ser_phy_location_id=ser_phy_location, ser_os_type_id = ser_os_type, ser_os_version_id = ser_os_version,ser_database_type_id=ser_database_type)
            db.session.add(new_server)
            db.session.commit()
            return redirect(url_for('serverinventory.index'))
        except Exception as e:
            error = "Something is wrong!"
            print(e)
    form = ServerForm()
    return render_template('serverinventory/add_server.html', form = form)


@serinv.route('/')
def index():
    servers = ServersInventory.query.order_by(ServersInventory.id.asc()).join(ServerPhyLocation, ServersInventory.ser_phy_location_id==ServerPhyLocation.id).join(ServerDatabaseType, ServersInventory.ser_database_type_id==ServerDatabaseType.id)\
        .join(ServerOsType, ServersInventory.ser_os_type_id==ServerOsType.id).join(ServerOsVersion, ServersInventory.ser_os_version_id==ServerOsVersion.id)
    
    return render_template('serverinventory/index.html',servers=servers)

app/serverinventory/templates/serverinventory/add_server.html
{% extends 'base.html' %}

{% block header %}Add new server{% endblock %}
{% block content_header %}Add new server{% endblock %}
{% block content %}

<form action="{{url_for('serverinventory.add_server')}}" method="POST">

    <div class="form-group">
        {% for item in form %}

        {{ item.label() }}
        {{ item(class='form-control') }}
        {% endfor %}
    </div>
 
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

app/serverinventory/templates/serverinventory/index.html
{% extends 'base.html' %}
{% block header %}
Server Inventory
{% endblock %}
{% block content_header %}

{% endblock %}

{% block content %}
<table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Hostname</th>
        <th scope="col">IP address</th>
        <th scope="col">OS Type</th>
        <th scope="col">OS Version</th>
        <th scope="col">Description</th>
        <th scope="col">CPU</th>
        <th scope="col">RAM</th>
        <th scope="col">Storage</th>
        <th scope="col">Server Localtion</th>
        <th scope="col">Server DB Type</th>
      </tr>
    </thead>
    <tbody>
{% for item in servers %}

      <tr>
        <th scope="row">{{loop.index}}</th>
        <td>{{item.ser_hostname}}</td>
        <td>{{item.ser_ip}}</td>
        <td>{{item.ser_os_type}}</td>
        <td>{{item.ser_os_version}}</td>
        <td>{{item.ser_description}}</td>
        <td>{{item.ser_cpu}}</td>
        <td>{{item.ser_ram}}</td>
        <td>{{item.ser_storage}}</td>
        <td>{{item.ser_phy_location}}</td>
        <td>{{item.ser_database_type}}</td>
      </tr>
 {% endfor %}
</tbody>
</table>

{% endblock %}