app/blog/forms.py
from wtforms import Form, StringField, TextAreaField

class PostForm(Form):
    title = StringField('Title')
    body = TextAreaField('Body')

app/blog/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Posts, Tags
from flask import request
from .forms import PostForm
from app import db
from flask import redirect,url_for
from flask_security import login_required,roles_required,roles_accepted


blogposts = Blueprint('blog',__name__,template_folder='templates')

@blogposts.route('/create', methods=['POST','GET'])
@login_required
@roles_accepted('editor','admin')
def create_post():
    if request.method == 'POST':
        t = request.form['title']
        b = request.form['body']
        try:
            new_post = Posts(title = t,body = b)
            db.session.add(new_post)
            db.session.commit()
            return redirect(url_for('blog.index'))
        except:
            error = "Something wrong!"

    form = PostForm()
    return render_template('blog/create_post.html', form = form)

@blogposts.route('/')
def index():
    q = request.args.get('q')
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1
    
    if q:
        posts = Posts.query.filter(Posts.title.contains(q) | Posts.body.contains(Posts.body.contains(q)))
    else:
        posts = Posts.query.order_by(Posts.created.desc())

    pages = posts.paginate(page=page, per_page=3)
    return render_template('blog/index.html',posts = posts,pages = pages)

@blogposts.route('/<slug>')
def post_details(slug):
    post_content = Posts.query.filter(Posts.slug == slug).first()
    tags = post_content.tags
    return render_template('blog/blog_post.html',post=post_content,tags=tags)

@blogposts.route('/tag/<slug>/')
def tag_details(slug):
    
    page = request.args.get('page')
    if page and page.isdigit():
        page = int(page)
    else:
        page = 1

    tag = Tags.query.filter(Tags.slug == slug).first()
    posts = tag.posts
    #posts = Posts.query.order_by(Posts.created.desc())

    pages = posts.paginate(page=page, per_page=3)
    return render_template('blog/tag_post.html', tag = tag, posts = posts,pages = pages)

app/blog/templates/blog/blog_post.html
{% extends 'base.html' %}
{% block header %}{{post.title}}{% endblock %}
{% block content_header %}
{{post.title}}
{% endblock %}

{% block content %}
<div class="tags">
    {% for tag in tags%}
<a href="{{ url_for( 'blog.tag_details', slug=tag.name) }}"<span class="badge badge-success">{{ tag.name }}</span></a>
    {% endfor %}
</div>

{{post.body}}
{% endblock %}

app/blog/templates/blog/create_post.html
{% extends 'base.html' %}

{% block title %} New Post{% endblock %}

{% block content_header %}New Post{% endblock %}
{% block content %}
<form action="{{url_for('blog.create_post')}}" method="POST">

    <div class="form-group">
        {% for item in form %}

        {{ item.label() }}
        {{ item(class='form-control') }}
        {% endfor %}
    </div>
 
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

{% endblock %}

app/blog/templates/blog/index.html
{% extends 'base.html' %}
{% block header %}
My BLOG
{% endblock %}
{% block content_header %}
My BLOG Posts
{% endblock %}

{% block content %}
{% for post in pages.items %}
<p>
    <a href="{{ url_for('blog.post_details',slug=post.slug)}}">{{post.title}}</a>
</p>
{% endfor %}
<nav aria-label="...">
    <ul class="pagination">
      <li class="page-item {% if not pages.has_prev %}disabled{% endif %}">
        <a class="page-link" href="./?page={{pages.prev_num}}" tabindex="-1" {% if not pages.has_prev %}aria-disabled="true"{% endif %}>Previous</a>
      </li>
      {% for page in pages.iter_pages(left_edge=1, right_edge=2, left_current=1, right_current=2) %}
      {% if page %}
      <li {% if page == pages.page %}class="page-item active" aria-current="page"{% endif %} >
        <a class="page-link" href="./?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
      </li>
      {% else %}
      <li class="page-item disabled">
      <a class="page-link" href="./?page={{page}}">...<span class="sr-only">(current)</span></a>
       </li>
      {% endif %}
      {% endfor %}
      <li class="page-item {% if not pages.has_next %}disabled{% endif %}">
        <a class="page-link" href="./?page={{pages.next_num}}" {% if not pages.has_prev %}aria-disabled="true"{% endif %}>Next</a>
      </li>
    </ul>
  </nav>
{% endblock %}

app/blog/templates/blog/tag_post.html
{% extends 'base.html' %}
{% block header %}{{tag.name}} | Posts{% endblock %} 
{% block content_header %}
Posts for: {{tag.name}}
{% endblock %}

{% block content %}
{% for post in pages.items %}
<p>
    <a href="{{ url_for('blog.post_details',slug=post.slug)}}">{{post.title}}</a>
</p>


{% endfor %}
<nav aria-label="...">
    <ul class="pagination">
      <li class="page-item {% if not pages.has_prev %}disabled{% endif %}">
        <a class="page-link" href="./?page={{pages.prev_num}}" tabindex="-1" {% if not pages.has_prev %}aria-disabled="true"{% endif %}>Previous</a>
      </li>
      {% for page in pages.iter_pages(left_edge=1, right_edge=2, left_current=1, right_current=2) %}
      {% if page %}
      <li {% if page == pages.page %}class="page-item active" aria-current="page"{% endif %} >
        <a class="page-link" href="./?page={{page}}">{{page}}<span class="sr-only">(current)</span></a>
      </li>
      {% else %}
      <li class="page-item disabled">
      <a class="page-link" href="./?page={{page}}">...<span class="sr-only">(current)</span></a>
       </li>
      {% endif %}
      {% endfor %}
      <li class="page-item {% if not pages.has_next %}disabled{% endif %}">
        <a class="page-link" href="./?page={{pages.next_num}}" {% if not pages.has_prev %}aria-disabled="true"{% endif %}>Next</a>
      </li>
    </ul>
  </nav>
{% endblock %}